### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by wjq1981** [molevol-ub/galeon#1]
Thanks for developing this software.

When I run the second step it reports an error. I am running 3 gene families, I wonder if this is the cause?
##
1.GALEON_ControlScript.py clusterfinder -a ingff3/ -g 100,200,500,800 -e enabled -p inpep/ -outdir cluster/ -f orange -pm False
2.GALEON_GetEvoStats.py -clust cluster/ -prot inpep/ -coords ingff3/

{'ClusterfinderResults': 'cluster/', 'CoordsDir': 'GFFs', 'ProtDir': 'inpep/', 'OutDirectory': 'MannWhitney_StatisticsResults'}
Traceback (most recent call last):
  File "/dev/hdd/wangjq/soft/galeon/GALEON_masterScripts/GALEON_GetEvoStats.py", line 103, in <module>
    I_GFF_list = [f"{coords_dir}/{i}" for i in os.listdir(f"{coords_dir}/") if i.endswith("collapsed.temp")]
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'GFFs/'
(galeon) [suma@suma-Nd 三 7月 24 20:47 13.uppasa]$ GALEON_GetEvoStats.py -clust cluster/ -prot inpep/ -coords ingff3/                                                 {'ClusterfinderResults': 'cluster/', 'CoordsDir': 'ingff3/', 'ProtDir': 'inpep/', 'OutDirectory': 'MannWhitney_StatisticsResults'}                                    ['inpep//CYP_fam.iqtree-fast_distancematrix.tsv', 'inpep//UGT_fam.iqtree-fast_distancematrix.tsv', 'inpep//OSC_fam.iqtree-fast_distancematrix.tsv']
OSC_fam
UGT_fam
CYP_fam
Traceback (most recent call last):
  File "/dev/hdd/wangjq/soft/galeon/GALEON_masterScripts/GALEON_GetEvoStats.py", line 713, in <module>
    CstGlob_value, DT2glob_value, DCglob_value, glob_pv, glob_sigf = GetStatistics_and_RunMWtest(kFAMILY, BEDfile, EvoDistfile, ClusterDictfile, gvalue_hint)
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dev/hdd/wangjq/soft/galeon/GALEON_masterScripts/GALEON_GetEvoStats.py", line 479, in GetStatistics_and_RunMWtest
    FamMembers = D_ScfFamGenes[tempKey]
                 ~~~~~~~~~~~~~^^^^^^^^^
KeyError: '12'

**Comment by V-JJ** [comment]
Hello!

Thanks for trying our software!
I've not faced this error so far, but I'll be glad to help. 

Current software version allows you to explore the physical distances of several families at once (3 in your case). 
- But, if you want to include the evolutionary distances, you should run the pipeline using only two families at once.
I think this is the fastest test for you to perform to check whether Galeon runs properly with your data. Another recommendation to speed up the test is to use "FastTree" (-t FastTree). 

So, you may consider to run this test in first place. Meanwhile, I'll try to find out the possible reasons of the error.

Thanks,
Vadim

**Comment by wjq1981** [comment]
Thank you very much for your prompt reply. I now understand the cause of the problem.

**Comment by V-JJ** [comment]
You're welcome!

V
